# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='Published_Date',
        ),
    ]
