# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160501_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.CharField(default=datetime.datetime(2016, 5, 1, 8, 14, 49, 612892, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
