# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(upload_to=b'news/%Y/%m/%d/'),
        ),
    ]
