# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160501_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Approved_Comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '\u041d\u0438\u0439\u0442\u043b\u044d\u043b', 'verbose_name_plural': '\u041d\u0438\u0439\u0442\u043b\u044d\u043b\u04af\u04af\u0434'},
        ),
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041d\u0438\u0439\u0442\u043b\u044d\u0433\u0447'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Created_Date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u04ae\u04af\u0441\u0433\u044d\u0441\u044d\u043d \u043e\u0433\u043d\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(upload_to=b'news/%Y/%m/%d/', verbose_name='\u0417\u0443\u0440\u0430\u0433'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Published_Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u041d\u0438\u0439\u0442\u043b\u044d\u0441\u044d\u043d \u043e\u0433\u043d\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(verbose_name='\u0411\u0438\u0447\u0432\u044d\u0440'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=200, verbose_name='\u0413\u0430\u0440\u0447\u0438\u0433'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.Post'),
        ),
    ]
