# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160501_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
