# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('Delivery_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Delivery_Reg_Time', models.DateTimeField(auto_now_add=True)),
                ('Delivery_Est_Date', models.DateField()),
                ('Delivery_Sender', models.CharField(max_length=45)),
                ('Delivery_Sender_Phone', models.CharField(max_length=8)),
                ('Delivery_From_Address', models.CharField(max_length=255)),
                ('Delivery_Recipient', models.CharField(max_length=45)),
                ('Delivery_Recipient_Phone', models.CharField(max_length=8)),
                ('Delivery_To_Address', models.CharField(max_length=255)),
                ('Delivery_Total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('Indication_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Indication', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('Shipment_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Shipment_Piece', models.IntegerField()),
                ('Shipment_Weight', models.FloatField()),
                ('Shipment_Type', models.CharField(max_length=45)),
                ('Shipment_Note', models.TextField(max_length=500)),
                ('Indication_ID', models.ManyToManyField(to='registration.Indication')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('Status_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('Worker_ID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Worker_Login', models.CharField(max_length=45)),
                ('Worker_FirstName', models.CharField(max_length=45)),
                ('Worker_LastName', models.CharField(max_length=45)),
                ('Worker_EMail', models.CharField(max_length=45)),
                ('Worker_Phone', models.CharField(max_length=8)),
                ('Worker_Password', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='Shipment_ID',
            field=models.ManyToManyField(to='registration.Shipment'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Status'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='Worker_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Worker'),
        ),
    ]
