# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': '\u0425\u04af\u0440\u0433\u044d\u043b\u0442', 'verbose_name_plural': '\u0425\u04af\u0440\u0433\u044d\u043b\u0442\u04af\u04af\u0434'},
        ),
        migrations.AlterModelOptions(
            name='indication',
            options={'verbose_name': '\u0428\u0438\u043d\u0436 \u0447\u0430\u043d\u0430\u0440', 'verbose_name_plural': '\u0428\u0438\u043d\u0436 \u0447\u0430\u043d\u0430\u0440\u0443\u0443\u0434'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': '\u0410\u0447\u0430\u0430', 'verbose_name_plural': '\u0410\u0447\u0430\u0430\u043d\u0443\u0443\u0434'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': '\u0422\u04e9\u043b\u04e9\u0432', 'verbose_name_plural': '\u0422\u04e9\u043b\u0432\u04af\u04af\u0434'},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='Worker_ID',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_Est_Date',
            field=models.DateField(verbose_name='\u0425\u04af\u0440\u0433\u044d\u0433\u0434\u044d\u0445 \u043e\u0433\u043d\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_From_Address',
            field=models.CharField(max_length=255, verbose_name='\u0418\u043b\u0433\u044d\u044d\u0433\u0447\u0438\u0439\u043d \u0445\u0430\u044f\u0433'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u0425\u04af\u0440\u0433\u044d\u043b\u0442\u0438\u0439\u043d \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_Recipient',
            field=models.CharField(max_length=45, verbose_name='\u0425\u04af\u043b\u044d\u044d\u043d \u0430\u0432\u0430\u0433\u0447\u0438\u0439\u043d \u043d\u044d\u0440'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_Recipient_Phone',
            field=models.CharField(max_length=8, verbose_name='\u0425\u04af\u043b\u044d\u044d\u043d \u0430\u0432\u0430\u0433\u0447\u0438\u0439\u043d \u0443\u0442\u0430\u0441\u043d\u044b \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_Reg_Time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0411\u04af\u0440\u0442\u0433\u044d\u0433\u0434\u0441\u044d\u043d \u043e\u0433\u043d\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_Sender',
            field=models.CharField(max_length=45, verbose_name='\u0418\u043b\u0433\u044d\u044d\u0433\u0447\u0438\u0439\u043d \u043d\u044d\u0440'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_Sender_Phone',
            field=models.CharField(max_length=8, verbose_name='\u0418\u043b\u0433\u044d\u044d\u0433\u0447\u0438\u0439\u043d \u0443\u0442\u0430\u0441\u043d\u044b \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_To_Address',
            field=models.CharField(max_length=255, verbose_name='\u0425\u04af\u043b\u044d\u044d\u043d \u0430\u0432\u0430\u0433\u0447\u0438\u0439\u043d \u0445\u0430\u044f\u0433'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_Total',
            field=models.FloatField(verbose_name='\u041d\u0438\u0439\u0442 \u0442\u04e9\u043b\u0431\u04e9\u0440'),
        ),
        migrations.AlterField(
            model_name='indication',
            name='Indication',
            field=models.CharField(max_length=45, verbose_name='\u0428\u0438\u043d\u0436 \u0447\u0430\u043d\u0430\u0440\u044b\u043d \u043d\u044d\u0440'),
        ),
        migrations.AlterField(
            model_name='indication',
            name='Indication_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u0428\u0438\u043d\u0436 \u0447\u0430\u043d\u0430\u0440\u044b\u043d \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Indication_ID',
            field=models.ManyToManyField(to='registration.Indication', verbose_name='\u0428\u0438\u043d\u0436 \u0447\u0430\u043d\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Shipment_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Shipment_Note',
            field=models.TextField(max_length=500, verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0442\u044d\u043c\u0434\u044d\u0433\u043b\u044d\u043b'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Shipment_Piece',
            field=models.IntegerField(verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0442\u043e\u043e'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Shipment_Type',
            field=models.CharField(max_length=45, verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0442\u04e9\u0440\u04e9\u043b'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Shipment_Weight',
            field=models.FloatField(verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0436\u0438\u043d'),
        ),
        migrations.AlterField(
            model_name='status',
            name='Status',
            field=models.CharField(max_length=45, verbose_name='\u0422\u04e9\u043b\u04e9\u0432\u0438\u0439\u043d \u043d\u044d\u0440'),
        ),
        migrations.AlterField(
            model_name='status',
            name='Status_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u0422\u04e9\u043b\u04e9\u0432\u0438\u0439\u043d \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
