# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160417_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='Shipment_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
    ]
