# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160417_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='Delivery_ID',
        ),
        migrations.AddField(
            model_name='delivery',
            name='Shipment_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.Shipment'),
            preserve_default=False,
        ),
    ]
