# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20160417_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u0425\u04af\u0440\u0433\u044d\u043b\u0442\u0438\u0439\u043d \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Shipment_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Shipment', verbose_name='\u0410\u0447\u0430\u0430\u043d\u0443\u0443\u0434'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Status', verbose_name='\u0422\u04e9\u043b\u04e9\u0432'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Shipment_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
    ]
