# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20160417_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Delivery_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u0425\u04af\u0440\u0433\u044d\u043b\u0442\u0438\u0439\u043d \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
    ]
