# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20160417_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('State_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='\u0410\u0439\u043c\u0430\u0433/\u043d\u0438\u0439\u0441\u043b\u044d\u043b\u0438\u0439\u043d \u0434\u0443\u0433\u0430\u0430\u0440')),
                ('State', models.CharField(max_length=45, verbose_name='\u0410\u0439\u043c\u0430\u0433/\u043d\u0438\u0439\u0441\u043b\u044d\u043b\u0438\u0439\u043d \u043d\u044d\u0440')),
            ],
            options={
                'verbose_name': '\u0410\u0439\u043c\u0430\u0433/\u043d\u0438\u0439\u0441\u043b\u044d\u043b',
            },
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='Shipment_ID',
        ),
        migrations.AddField(
            model_name='shipment',
            name='Delivery_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Shipments', to='registration.Delivery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indication',
            name='Indication_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u0428\u0438\u043d\u0436 \u0447\u0430\u043d\u0430\u0440\u044b\u043d \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Shipment_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='status',
            name='Status_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u0422\u04e9\u043b\u04e9\u0432\u0438\u0439\u043d \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
    ]
