# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20160419_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='Delivery_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Delivery', verbose_name='\u0425\u04af\u0440\u0433\u044d\u043b\u0442\u0438\u0439\u043d \u0434\u0443\u0433\u0430\u0430\u0440'),
        ),
    ]
