# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20160421_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('Type_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='\u0422\u04e9\u0440\u043b\u0438\u0439\u043d \u0434\u0443\u0433\u0430\u0430\u0440')),
                ('Type', models.CharField(max_length=45, verbose_name='\u0422\u04e9\u0440\u043b\u0438\u0439\u043d \u043d\u044d\u0440')),
            ],
            options={
                'verbose_name': '\u0410\u0447\u0430\u0430\u043d\u044b \u0442\u04e9\u0440\u04e9\u043b',
                'verbose_name_plural': '\u0410\u0447\u0430\u0430\u043d\u044b \u0442\u04e9\u0440\u043b\u04af\u04af\u0434',
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='Shipment_Piece',
        ),
    ]
