# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20160502_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='Shipment_Type',
        ),
        migrations.AddField(
            model_name='shipment',
            name='Type_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.Type', verbose_name='\u0410\u0447\u0430\u0430\u043d\u044b \u0442\u04e9\u0440\u04e9\u043b'),
            preserve_default=False,
        ),
    ]
