# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20160502_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='Recipient_Signature',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.get_image_path, verbose_name='\u0413\u0430\u0440\u044b\u043d \u04af\u0441\u044d\u0433'),
        ),
    ]
