# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20160504_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='Delivery_To_Address',
        ),
        migrations.AddField(
            model_name='delivery',
            name='To_State_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_state', to='registration.State', verbose_name='\u0425\u043e\u0442/\u0410\u0439\u043c\u0430\u0433'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='To_SubState_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_substate', to='registration.SubState', verbose_name='\u0414\u04af\u04af\u0440\u044d\u0433/\u0421\u0443\u043c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='State_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_state', to='registration.State', verbose_name='\u0425\u043e\u0442/\u0410\u0439\u043c\u0430\u0433'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='SubState_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_substate', to='registration.SubState', verbose_name='\u0414\u04af\u04af\u0440\u044d\u0433/\u0421\u0443\u043c'),
        ),
    ]
