# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20160504_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': '\u0410\u0439\u043c\u0430\u0433/\u043d\u0438\u0439\u0441\u043b\u044d\u043b', 'verbose_name_plural': '\u0410\u0439\u043c\u0430\u0433/\u043d\u0438\u0439\u0441\u043b\u044d\u043b'},
        ),
        migrations.AlterModelOptions(
            name='substate',
            options={'verbose_name': '\u0421\u0443\u043c/\u0434\u04af\u04af\u0440\u044d\u0433', 'verbose_name_plural': '\u0421\u0443\u043c/\u0434\u04af\u04af\u0440\u044d\u0433'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='Status_Reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u04e9\u043b\u0432\u0438\u0439\u043d \u0448\u0430\u043b\u0442\u0433\u0430\u0430\u043d'),
        ),
    ]
