# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_state_substate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='SubState_ID',
        ),
        migrations.AddField(
            model_name='substate',
            name='State_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.State', verbose_name='\u0425\u043e\u0442/\u0410\u0439\u043c\u0430\u0433'),
            preserve_default=False,
        ),
    ]
