# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20160504_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='From_Address',
            field=models.CharField(default=1, max_length=255, verbose_name='\u0418\u043b\u0433\u044d\u044d\u0433\u0447\u0438\u0439\u043d \u0445\u0430\u044f\u0433'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='To_Address',
            field=models.CharField(default=1, max_length=255, verbose_name='\u0425\u04af\u043b\u044d\u044d\u043d \u0430\u0432\u0430\u0433\u0447\u0438\u0439\u043d \u0445\u0430\u044f\u0433'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='State_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.State', verbose_name='\u0425\u043e\u0442/\u0410\u0439\u043c\u0430\u0433'),
        ),
    ]
