# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0023_auto_20160504_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0425\u044d\u0440\u044d\u0433\u043b\u044d\u0433\u0447'),
            preserve_default=False,
        ),
    ]
