# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_delivery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0425\u044d\u0440\u044d\u0433\u043b\u044d\u0433\u0447'),
        ),
    ]
